version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        user: root
    working_directory: ~/eventuate-examples-docker-images
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish artifacts
          command: |
            ./.circleci/upgrade-docker-compose.sh
            TERM=dumb ./deploy-artifacts.sh
